# Generated by Django 3.1.4 on 2020-12-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facebook_token',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='user',
            name='gmail_token',
            field=models.CharField(max_length=2048),
        ),
    ]
