# Generated by Django 3.1.4 on 2021-01-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201230_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coins',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
