# Generated by Django 3.1.4 on 2021-01-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210102_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankinfo',
            name='CVV',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='userbankinfo',
            name='account_number',
            field=models.CharField(max_length=20),
        ),
    ]
