# Generated by Django 3.1.4 on 2021-01-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210106_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_verfiied',
            new_name='email_verified',
        ),
    ]
