# Generated by Django 3.1.4 on 2021-01-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210107_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coins',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook_token',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gmail_token',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
