export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const GET_ERROR = "GET_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const BECOME_SELLER_SUCCESS = "BECOME_SELLER_SUCCESS"