# Generated by Django 3.1.4 on 2020-12-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('out of stock', 'out of stock'), ('timeout', 'timeout'), ('inactive', 'inactive'), ('active', 'active')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('acution', 'auction'), ('limited', 'limited')], max_length=20, null=True),
        ),
    ]
