# Generated by Django 3.1.4 on 2021-01-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='task_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
