# Generated by Django 3.1.4 on 2021-01-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='firebasekey',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
